// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqqitvsthmyrbcbalcbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxcWl0dnN0aG15cmJjYmFsY2JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMTgzNzMsImV4cCI6MjA1Nzg5NDM3M30.2LC1m3kOns9vk-V8MsU2LXbkLa5bRVvmdDbp8-7akZw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);